---
title: "note12"
author: "Matts966"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output:
  pdf_document:
    latex_engine: lualatex
  word_document: default
documentclass: ltjsarticle
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

```{r}
set.seed(123)

# type=oはオーバーラップ
l <- 3
d <- rpois(50, lambda=l)
hist(d, ylim=c(0, 14), breaks=c(-0.5:8.5), xlab="x", ylab="freq.", main="")
par(new=T)
x <- seq(0, 8, 1)
y <- 50*dpois(x, lambda=2) 
plot(x, y, xlab="", ylab="", xlim=c(-0.5, 8.5), ylim=c(0, 14), type="o", col="grey", cex=0.5)


hist(d, ylim=c(0, 14), breaks=c(-0.5:8.5), xlab="x", ylab="freq.", main="")
par(new=T)
x <- seq(0, 8, 1)
y <- 50*dpois(x, lambda=3) 
plot(x, y, xlab="", ylab="", xlim=c(-0.5, 8.5), ylim=c(0, 14), type="o", col="grey", cex=0.5)


hist(d, ylim=c(0, 14), breaks=c(-0.5:8.5), xlab="x", ylab="freq.", main="")
par(new=T)
x <- seq(0, 8, 1)
y <- 50*dpois(x, lambda=3.5) 
plot(x, y, xlab="", ylab="", xlim=c(-0.5, 8.5), ylim=c(0, 14), type="o", col="grey", cex=0.5)


hist(d, ylim=c(0, 14), breaks=c(-0.5:8.5), xlab="x", ylab="freq.", main="")
par(new=T)
x <- seq(0, 8, 1)
y <- 50*dpois(x, lambda=4) 
plot(x, y, xlab="", ylab="", xlim=c(-0.5,8.5), ylim=c(0, 14), type="o", col="grey", cex=0.5)
```
```{r}
set.seed(123)
l <- 3
d <- rpois(50, lambda=l)

logL <- sum(dpois(d, 2.0, log=T))
logL
logL <- sum(dpois(d, 3.0, log=T))
logL
logL <- sum(dpois(d, 3.5, log=T))
logL
logL <- sum(dpois(d, 4.0, log=T))
logL
# AICを計算して最小を提示
AIC = -2 * (-97.71459) + 2 * 2
AIC
# よってlambda3.0でAIC最小
```

```{r}
set.seed(123)
l <- 3
d <- rpois(50, lambda=l)

logL <- function(m) sum(dpois(d, m, log=T))
lambda <- seq(2, 5, 0.1)
plot(lambda, sapply(lambda, logL), type="l", xlim=c(2, 5), xlab="lambda", ylab="logL")
```

```{r}
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
```

```{r}
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
d <- read.csv("table10-2.csv")
result <- glm(cbind(d$dead, 1-d$dead) ~ d$dose, family=binomial(logit))
logLik(result)
AIC = -2 * (-6.781799) + 2 * 2
AIC
```

```{r}
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
d <- read.csv("table10-3.csv")
result <- glm(d$flw ~ d$wt, family=poisson)
logLik(result)
AIC = -2 * (-82.84586) + 2 * 2
AIC
```

```{r}
library(lme4)
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")

d <- read.csv("table11-1.csv")
plot(d$y ~ d$x, pch=as.character(d$block))
res.1 <- glmer(d$y ~d$x + (1|d$block), family=gaussian(link = identity))
res.2 <- lmer(d$y ~ d$x + (1|d$block))
```

```{r}
summary(res.1)
```

```{r}
summary(res.2)
```


```{r}
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
d <- read.csv("table11-3.csv")
matrix(c(d$y), nrow=4, ncol=12)
```


# ここから
```{r}
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
library(lme4)
library(glmmML)
d <- read.csv("table11-3.csv")
mother <- as.factor(d$mother)
wt <- d$wt
y <- d$y
res.1 <-glmer(y ~ wt + (1|mother), family=binomial(logit))
res.1 <- summary(res.1)
res.2 <-glmmML(y ~ wt , cluster=mother)
plot(d$wt, d$y, xlab="weight", ylab="sex ratio", xlim=c(0, 0.6))
pred.wt <- seq(0, 0.6, 0.01)
pred.y1 <- 1/(1+exp(-(res.1$coefficient[1] + res.1$coefficient[2]*pred.wt)))
pred.y2 <- 1/(1+exp(-(res.2$coefficient[1] + res.2$coefficient[2]*pred.wt)))
lines(pred.wt, pred.y1, lwd=2, col="black")
lines(pred.wt, pred.y2, lwd=2, col="grey", lty=3)
```

```{r}
# 演習11-1
setwd("/Users/masahiromatsui/Dropbox/R/Rで学ぶ統計学入門図版作成用（改訂版）/付録/")
library(lme4)
library(glmmML)
d <- read.csv("enshu11-1.csv")
cond <- as.factor(d$cond)
x <- d$x
y <- as.factor(d$y)
res.1 <-glmer(y ~ x + (1|cond), family=binomial(logit))
res.1 <- summary(res.1)
res.2 <-glmmML(y ~ x , cluster=cond)
res.1
print('------------------------------------------------------------------------------------------------')
res.2
```
【考察】
p-value 0.0395 で効果が検出された。
